### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by emiliazm** [Danie12345/bookit-api-be#19]
Hello!

We are a group of 5 people:
@joshuaivie 
@Danie12345 
@JuanLPalacios 
@Adanzeakonobi 
@emiliazm 

These are the links related to our project:
[Kanban board](https://github.com/users/Danie12345/projects/4/views/1)
[Back end repo](https://github.com/Danie12345/bookit-api-be)
[Front end repo](https://github.com/Danie12345/bookit-fe)

Initial Board:
![Image](https://user-images.githubusercontent.com/35552263/190486489-5c7e34a5-5727-44b7-9e57-5fa7a435fd21.png)

---

Table View:
![image](https://user-images.githubusercontent.com/35552263/190486859-45dd628c-45b1-4df1-b420-d000cc55ed9c.png)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
